version: "3.8"

services:
  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    container_name: flask_app
    restart: always
    environment:
      # Point Flask-Limiter to the Redis service
      - REDIS_URL=redis://redis:6379/0
      - PORT=8443
    ports:
      - "8443:8443"
    depends_on:
      - redis

volumes:
  redis_data:
